### ISSUE TITLE
"curl_setopt_array():" Error

### ISSUE THREAD

**Issue by GeorgeD121** [joshuabaker/craft-essence#7]
I'm receiving an error on my staging site when trying to use essence in a small piece of my craft code: 

```
   {% set secondCta = block.secondaryCta %}
{% set url = secondCta.url %}

{% set media = craft.essence.embed(url, {
        'type': 'video' 
}) %}

{% if media.type is defined  %}
    <a href="#" data-toggle="modal" data-target=".video-modal-lg">{{ secondCta.text }}<i class="icon-right"></i></a>
{% else %}
```

![screen shot 2015-06-05 at 17 28 07](https://cloud.githubusercontent.com/assets/4412306/8010461/426b7664-0ba8-11e5-9b2d-c75efbab3596.png)

Code works fine locally, but bombs to the above error on staging. 
Wondering if you had any insight to this issue?

Many thanks

**Comment by joshuabaker** [comment]
`open_basedir` is a php.ini directive, which is not set by default. This is almost certainly something you need to take up with your hosting provider.
